In [1]:
import numpy as np
from scipy.spatial.transform import Rotation

Начальные параметры:
    0: Задана точка в прострастве с координатами x = 1, y = 2, z = 3;
    1: Простраство поворачивается по оси Y на угол в 45 градусов, т.е. pi/4;
    2: Начало координат пространства сдвигается на вектор (3, 2, 1).
Найти:
    Координаты точки в новом прострастве.

In [2]:
point =  np.array([1, 2, 3])
angle = np.pi/4
vector = np.array([3, 2, 1])

Вращение пространства вокруг оси можно выполнить с помощью углов Эйлера. Поскольку происходит вращение вокруг одной лишь оси Y, то матрица поворота будет иметь следующий вид:
rot = { 
        ( cos(a),    0,   sin(a) ),
        ( 0,         1,   0      ),
        ( -sin(a),   0,   cos(a) ),
      },
где a = angle = np.pi/4 - угол вращение по оси Y.

Получим матрицу со следующими значениями:

In [11]:
rot = Rotation.from_euler('y', [angle]).as_matrix()
rot

array([[[ 0.70710678,  0.        ,  0.70710678],
        [ 0.        ,  1.        ,  0.        ],
        [-0.70710678,  0.        ,  0.70710678]]])

Новые координаты точки после вращение (x', y', z') будут равны поизведению матрицы поворота и вектора с координатами точки:
rot_point = {
                (x',         (x,
                 y', = rot *  y,
                 z')          z)
            }

In [17]:
rot_point = np.squeeze(np.matmul(rot, point))
rot_point

array([2.82842712, 2.        , 1.41421356])

Начало координат сдвигается с точки (0, 0, 0) в точку (3, 2, 1). Это означает, что новые координаты точки new_point = (x'', y'', z'') =  rot_point - vector.

In [19]:
new_point = rot_point - vector
new_point

array([-0.17157288,  0.        ,  0.41421356])

Таким образом координаты точки изменились с (3, 2, 1) на (-0.17, 0, 0.41).